# Site settings
title: AMDiS-Workshop 2016
short-title: AMDiS-Workshop 2016
email: simon.praetorius@tu-dresden.de
description: > # this means to ignore newlines until "baseurl:"
  Der AMDiS Workshop bietet eine Einführung in die Finite-Elemente Software AMDiS. 
baseurl: "amdis_workshop_16"
url: "http://spraetor.github.io"
author: Simon Praetorius
github_username: spraetor

# Build settings
markdown: kramdown

sass:
    style: compressed
    
#comments:
  #provider: disqus
  #disqus:
    #short_name: spraetor
